apiVersion: apps/v1 
kind: Deployment
metadata:
  name: valaxy-regapp
  labels: 
     app: regapp

spec:
  replicas: 2 
  selector:
    matchLabels:
      app: regapp

  template:
    metadata:
      labels:
        app: regapp
    spec:
      imagePullSecrets:
      - name: ghcr-creds

      containers:
      - name: regapp
        image: ghcr.io/swaroopsakhare25/formfillapp:sha-26beca9479482742ba76bda253e7b663a9b11623 
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: ghcr-creds
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
